#!/bin/sh
set -eu

wiki_root=docs/wiki
report=$wiki_root/lint-report.md
tmp_file=/tmp/wiki-lint.$$
trap 'rm -f "$tmp_file"' EXIT
pages=$(find "$wiki_root" -type f -name '*.md' ! -name 'lint-report.md' | sort)
names=$( { printf '%s\n' "$pages" | sed -E 's|.*/||; s|\.md$||'; echo lint-report; } | sort )
errors=0
warnings=0

{
  echo "# Wiki lint report"
  echo
  echo "Generated by \`scripts/wiki-lint.sh\`."
  echo
  echo "## Results"
  echo
} > "$tmp_file"

for page in $pages; do
  case "$page" in
    "$wiki_root/CLAUDE.md"|"$wiki_root/index.md"|"$wiki_root/log.md"|"$wiki_root/KNOWLEDGE-PIPELINE.md"|"$wiki_root/raw/"*|*/README.md) continue ;;
  esac
  if ! grep -q '^source: ' "$page"; then
    echo "- ERROR missing source metadata: \`$page\`" >> "$tmp_file"
    errors=$((errors + 1))
  fi
  if grep -q '^status: ' "$page"; then
    status=$(sed -n 's/^status: //p' "$page" | head -1)
    case "$status" in current|accepted|archived) ;; *)
      echo "- ERROR invalid status \`$status\`: \`$page\`" >> "$tmp_file"
      errors=$((errors + 1))
    esac
  fi
done

duplicate_titles=$(find "$wiki_root" -type f -name '*.md' -exec sed -n 's/^title: //p' {} \; | sort | uniq -d)
if [ -n "$duplicate_titles" ]; then
  printf '%s\n' "$duplicate_titles" | sed 's/^/- ERROR duplicate title: `/' | sed 's/$/`/' >> "$tmp_file"
  errors=$((errors + 1))
fi

links=$(grep -rhoE '\[\[[^]|#]+\]\]' "$wiki_root" --include='*.md' | sed -E 's/^\[\[//; s/\]\]$//' | sort -u || true)
for link in $links; do
  if ! printf '%s\n' "$names" | grep -Fxq "$link"; then
    echo "- ERROR broken wikilink: \`[[$link]]\`" >> "$tmp_file"
    errors=$((errors + 1))
  fi
done

for page in $pages; do
  base=$(basename "$page" .md)
  case "$base" in CLAUDE|index|log|KNOWLEDGE-PIPELINE|README) continue ;; esac
  if ! grep -RFql "[[$base]]" "$wiki_root" --include='*.md'; then
    echo "- WARNING possible orphan page: \`$page\`" >> "$tmp_file"
    warnings=$((warnings + 1))
  fi
done

if [ "$errors" -eq 0 ] && [ "$warnings" -eq 0 ]; then
  echo "- PASS: no broken links, duplicate titles, invalid statuses, missing source metadata, or possible orphan pages found." >> "$tmp_file"
fi
echo >> "$tmp_file"
echo "Errors: $errors" >> "$tmp_file"
echo "Warnings: $warnings" >> "$tmp_file"
mv "$tmp_file" "$report"
trap - EXIT
echo "wiki lint: $errors error(s), $warnings warning(s)"
[ "$errors" -eq 0 ]
