#!/bin/sh
set -eu

# Invariant: this script's own generated $report (lint-report.md) is never
# consumed as input to any lint category below. It lives under $wiki_root
# and matches every `--include='*.md'`/`find ... -name '*.md'` glob used
# to scan the vault, so every one of those whole-vault scans (not just the
# page-content loop, which already excluded it via $report_name) must
# explicitly exclude it by name too — otherwise a prior run's own error
# text (which often quotes an offending token verbatim, e.g. a broken
# `[[slug]]` or a bad `title:` line) can itself look like real page
# content on the *next* run, producing a self-perpetuating false result
# (a stale false-positive error, or a false-negative that hides a real
# orphan) fed entirely by the tool's own prior output. Every grep/find
# below that walks $wiki_root as a whole (as opposed to iterating the
# already-filtered $pages list) must use $report_name as an exclusion, not
# a broader page exclusion — this is a defect in what generated tooling
# artifacts are, never a reason to exempt any real page.
root=$(CDPATH= cd "$(dirname "$0")/.." && pwd)
wiki_root=docs/wiki
report=$wiki_root/lint-report.md
report_name=$(basename "$report")
tmp_file=/tmp/wiki-lint.$$
trap 'rm -f "$tmp_file"' EXIT
pages=$(find "$wiki_root" -type f -name '*.md' ! -name "$report_name" | sort)
names=$( { printf '%s\n' "$pages" | sed -E 's|.*/||; s|\.md$||'; echo lint-report; } | sort )
errors=0
warnings=0

{
  echo "# Wiki lint report"
  echo
  echo "Generated by \`scripts/wiki-lint.sh\`."
  echo
  echo "## Results"
  echo
} > "$tmp_file"

for page in $pages; do
  case "$page" in
    "$wiki_root/CLAUDE.md"|"$wiki_root/index.md"|"$wiki_root/log.md"|"$wiki_root/KNOWLEDGE-PIPELINE.md"|"$wiki_root/raw/"*|*/README.md) continue ;;
  esac
  if ! grep -q '^source: ' "$page"; then
    echo "- ERROR missing source metadata: \`$page\`" >> "$tmp_file"
    errors=$((errors + 1))
  fi
  source_path=$(sed -n 's/^source: //p' "$page" | head -1)
  if [ -n "$source_path" ] && [ ! -e "$root/$source_path" ]; then
    echo "- ERROR nonexistent provenance source: \`$page\` → \`$source_path\`" >> "$tmp_file"
    errors=$((errors + 1))
  fi
  if grep -q '^status: ' "$page"; then
    status=$(sed -n 's/^status: //p' "$page" | head -1)
    case "$status" in current|accepted|archived|contradicted) ;; *)
      echo "- ERROR invalid status \`$status\`: \`$page\`" >> "$tmp_file"
      errors=$((errors + 1))
    esac
  fi
  if grep -q '^status: contradicted' "$page" && ! grep -q '^contradicts: ' "$page"; then
    echo "- ERROR contradicted page lacks contradicts metadata: \`$page\`" >> "$tmp_file"
    errors=$((errors + 1))
  fi
done

duplicate_titles=$(find "$wiki_root" -type f -name '*.md' ! -name "$report_name" -exec sed -n 's/^title: //p' {} \; | sort | uniq -d)
if [ -n "$duplicate_titles" ]; then
  printf '%s\n' "$duplicate_titles" | sed 's/^/- ERROR duplicate title: `/' | sed 's/$/`/' >> "$tmp_file"
  errors=$((errors + 1))
fi

links=$(grep -rhoE '\[\[[^]|#]+\]\]' "$wiki_root" --include='*.md' --exclude="$report_name" | sed -E 's/^\[\[//; s/\]\]$//' | sort -u || true)
for link in $links; do
  if ! printf '%s\n' "$names" | grep -Fxq "$link"; then
    echo "- ERROR broken wikilink: \`[[$link]]\`" >> "$tmp_file"
    errors=$((errors + 1))
  fi
done

for page in $pages; do
  base=$(basename "$page" .md)
  case "$base" in CLAUDE|index|log|KNOWLEDGE-PIPELINE|README) continue ;; esac
  if ! grep -RFql "[[$base]]" "$wiki_root" --include='*.md' --exclude="$report_name"; then
    echo "- WARNING possible orphan page: \`$page\`" >> "$tmp_file"
    warnings=$((warnings + 1))
  fi
done

if [ "$errors" -eq 0 ] && [ "$warnings" -eq 0 ]; then
  echo "- PASS: no broken links, duplicate titles, invalid statuses, missing source metadata, or possible orphan pages found." >> "$tmp_file"
fi
echo >> "$tmp_file"
echo "Errors: $errors" >> "$tmp_file"
echo "Warnings: $warnings" >> "$tmp_file"
mv "$tmp_file" "$report"
trap - EXIT
echo "wiki lint: $errors error(s), $warnings warning(s)"
[ "$errors" -eq 0 ]
